version: "3"
services:
  client:
    container_name: todofrontend
    image: index.docker.io/baristure/todofrontend:latest
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
  api:
    container_name: todo-backend
    image: index.docker.io/baristure/todo-backend:latest
    restart: always
    ports:
      - "5000:5000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30