name: ToDo App CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy-back:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test backend and frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd ./backend && npm install && npm test
      - run: cd ./frontend && npm install && npm test
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          build: npm run build
          start: npm start
